env:
    browser: true
    commonjs: true
    es6: true
    mocha: true
    node: true
extends: 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
plugins:
    - react
    - react-hooks

    
rules:
    "indent": 2
    "react-hooks/rules-of-hooks": error
    "react-hooks/exhaustive-deps": warn
    
